[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.12.0"

[[redirects]]
  from = "https://stentor.live/*"
  to = "https://www.stentor.live/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/customers"
  to = "/for-theatres"
  status = 301
  force = true
