/**
 * Privacy & Terms content. The body of each section is rendered with
 * set:html and styled by the `.legal-prose` utility in global.css —
 * use plain HTML (<p>, <ul>, <ol>, <a>, <strong>, <code>) inside.
 *
 * This is template boilerplate. Replace with your own legal text or
 * one generated by your provider (Termly, Iubenda, your lawyer…).
 */

export type LegalSection = {
  id: string;
  title: string;
  body: string;
};

export type LegalPage = {
  eyebrow: string;
  title: string;
  effectiveDate: string;
  intro: string;
  sections: LegalSection[];
  contact: {
    title: string;
    body: string;
  };
};

// ─── Privacy Policy ────────────────────────────────────────────────────────
export const privacy: LegalPage = {
  eyebrow: "Legal · Privacy",
  title: "Privacy Policy",
  effectiveDate: "Effective May 1, 2026",
  intro:
    "This policy explains what data Lambda collects, how we use it, and the choices you have. We tried to write it in plain English. Where legalese was unavoidable, we left a footnote.",
  sections: [
    {
      id: "information-we-collect",
      title: "1. Information we collect",
      body: `
        <p>We collect three buckets of data:</p>
        <ul>
          <li><strong>Account information</strong> — your name, work email, company, and the payment method you provide when upgrading from the Free plan.</li>
          <li><strong>Usage data</strong> — request volume, function execution counts, error rates, and similar telemetry needed to operate and bill the service.</li>
          <li><strong>Content you upload</strong> — your code, schemas, database rows, logs, and any files you push to Lambda Storage. This is your data; we process it on your behalf.</li>
        </ul>
        <p>We do not collect biometric data, precise location, or content from third-party services unless you explicitly connect them.</p>
      `,
    },
    {
      id: "how-we-use",
      title: "2. How we use your information",
      body: `
        <p>We use your information to:</p>
        <ul>
          <li>Run the Lambda platform — execute your code, store your data, send you transactional emails about deploys and incidents.</li>
          <li>Bill you accurately and detect fraud or abuse.</li>
          <li>Improve the product — aggregated, anonymized usage data informs which features we build next.</li>
          <li>Comply with the law — tax records, audit trails, lawful subpoenas.</li>
        </ul>
        <p>We do not sell your data, and we do not use your code or database contents to train AI models.</p>
      `,
    },
    {
      id: "sharing",
      title: "3. Sharing & disclosure",
      body: `
        <p>We share data only with vendors that help us run the service — payment processors, transactional email providers, error monitoring, and customer support tooling. Each is bound by a Data Processing Agreement and listed in our <a href="#subprocessors">subprocessors page</a>.</p>
        <p>We will disclose data in response to a valid legal process. If we receive a subpoena that targets your account, we will notify you unless legally prohibited.</p>
      `,
    },
    {
      id: "retention",
      title: "4. Data retention",
      body: `
        <p>Account data is kept while your account is active and for 30 days after cancellation, after which it is permanently deleted. Backups are pruned within 90 days. Anonymized analytics may be retained indefinitely.</p>
        <p>You can export a full Postgres dump and Storage archive at any time from the dashboard.</p>
      `,
    },
    {
      id: "your-rights",
      title: "5. Your rights",
      body: `
        <p>Depending on where you live, you may have the right to:</p>
        <ul>
          <li>Access the personal data we hold about you</li>
          <li>Correct inaccurate data</li>
          <li>Delete your account and associated data</li>
          <li>Export your data in a portable format</li>
          <li>Object to certain processing or withdraw consent</li>
        </ul>
        <p>To exercise any of these rights, email <a href="mailto:privacy@lambda.dev">privacy@lambda.dev</a>. We respond within 30 days.</p>
      `,
    },
    {
      id: "cookies",
      title: "6. Cookies & tracking",
      body: `
        <p>Our marketing site uses a single first-party analytics cookie to count unique visitors. The product dashboard uses session cookies strictly necessary to keep you signed in.</p>
        <p>We do not use third-party advertising trackers. We do not use Google Analytics. There is no banner because there is nothing to consent to.</p>
      `,
    },
    {
      id: "international",
      title: "7. International data transfers",
      body: `
        <p>Lambda is a US-headquartered company with infrastructure in 38 regions worldwide. By default, your data is stored in the region closest to where you sign up. Enterprise customers can pin a primary region and prevent cross-border replication.</p>
        <p>Where data crosses borders, transfers are governed by Standard Contractual Clauses and our published <a href="#dpa">DPA</a>.</p>
      `,
    },
    {
      id: "children",
      title: "8. Children's privacy",
      body: `
        <p>Lambda is a developer tool intended for use in a professional context. We do not knowingly collect data from children under 16. If you believe we have collected such data, contact us and we will delete it.</p>
      `,
    },
    {
      id: "changes",
      title: "9. Changes to this policy",
      body: `
        <p>We may update this policy as the product evolves. Material changes will be announced 30 days in advance via email and a banner in the dashboard. Past versions are kept in our <a href="#changelog">policy changelog</a>.</p>
      `,
    },
  ],
  contact: {
    title: "Questions?",
    body:
      'Email <a href="mailto:privacy@lambda.dev">privacy@lambda.dev</a> or write to Lambda Systems, Inc., Attn: Privacy, 200 Berry Street, Suite 400, Brooklyn, NY 11217.',
  },
};

// ─── Terms of Service ──────────────────────────────────────────────────────
export const terms: LegalPage = {
  eyebrow: "Legal · Terms",
  title: "Terms of Service",
  effectiveDate: "Effective May 1, 2026",
  intro:
    "These terms govern your use of Lambda. They are not the most exciting thing you will read today, but they are short by industry standards. Please skim them.",
  sections: [
    {
      id: "acceptance",
      title: "1. Acceptance of terms",
      body: `
        <p>By creating a Lambda account or using the platform you agree to these Terms and to our <a href="/privacy">Privacy Policy</a>. If you are using Lambda on behalf of an organization, you represent that you have authority to bind that organization to these Terms.</p>
        <p>If you do not agree, do not use the service.</p>
      `,
    },
    {
      id: "account",
      title: "2. Your account",
      body: `
        <p>You are responsible for activity under your account, for keeping your credentials secure, and for the actions of users you invite. Notify us immediately at <a href="mailto:security@lambda.dev">security@lambda.dev</a> if you suspect unauthorized access.</p>
        <p>You must be at least 16 years old. Free-tier accounts are limited to one per person; commercial workspaces require a billed Pro or Enterprise subscription.</p>
      `,
    },
    {
      id: "billing",
      title: "3. Subscription & billing",
      body: `
        <p>Paid plans are billed monthly or annually in advance. Usage above the included tier (e.g. extra requests, storage) is billed in arrears at the rates published on our <a href="/pricing">Pricing page</a>.</p>
        <p>Annual subscriptions auto-renew unless cancelled at least 24 hours before the renewal date. Refunds are issued for service outages that breach the SLA, and at our discretion in cases of accidental over-billing.</p>
        <p>Taxes are added based on your billing address.</p>
      `,
    },
    {
      id: "acceptable-use",
      title: "4. Acceptable use",
      body: `
        <p>You may not use Lambda to:</p>
        <ul>
          <li>Send spam, host phishing pages, or engage in deceptive practices</li>
          <li>Distribute malware, run a botnet, or carry out attacks against third parties</li>
          <li>Mine cryptocurrency or run workloads that exist primarily to generate compute load</li>
          <li>Process content that is illegal where you operate or where Lambda's infrastructure runs</li>
          <li>Reverse-engineer, scrape, or attempt to derive source code from the platform</li>
        </ul>
        <p>We may suspend or terminate accounts that violate these rules. Repeat or egregious violations forfeit any unused prepaid balance.</p>
      `,
    },
    {
      id: "your-content",
      title: "5. Your content",
      body: `
        <p>You retain all rights to the code, data, and content you upload to Lambda. You grant us a limited license to host, transmit, and process that content solely as needed to operate the service.</p>
        <p>You are responsible for ensuring you have the right to use any content you upload, and for complying with applicable laws (privacy, export controls, IP).</p>
      `,
    },
    {
      id: "ip",
      title: "6. Our intellectual property",
      body: `
        <p>The Lambda platform, dashboard, CLI, SDKs, and documentation are protected by copyright, trademark, and other laws. We grant you a non-exclusive, non-transferable license to use them for the duration of your subscription.</p>
        <p>Open-source components are governed by their respective licenses, which take precedence where they conflict with these Terms.</p>
      `,
    },
    {
      id: "availability",
      title: "7. Service availability",
      body: `
        <p>We target 99.99% monthly uptime on Pro and Enterprise plans, measured against the multi-region edge gateway. Free-tier availability is best-effort.</p>
        <p>Scheduled maintenance is announced 7 days in advance. Emergency maintenance for security fixes may be performed without notice. SLA credits are issued automatically when uptime falls below the target.</p>
      `,
    },
    {
      id: "termination",
      title: "8. Termination",
      body: `
        <p>You may cancel any time from <strong>Settings → Billing → Cancel</strong>. Your data remains available for 30 days after cancellation; after that, it is permanently deleted.</p>
        <p>We may terminate or suspend accounts for material breach of these Terms, non-payment, or as required by law. Where reasonable, we will give you 14 days' notice and a chance to cure.</p>
      `,
    },
    {
      id: "warranties",
      title: "9. Disclaimers",
      body: `
        <p>The service is provided "as is" without warranty of any kind, express or implied, including warranties of merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the service will be uninterrupted, error-free, or perfectly secure — only that we will work hard to keep it that way.</p>
      `,
    },
    {
      id: "liability",
      title: "10. Limitation of liability",
      body: `
        <p>To the maximum extent permitted by law, Lambda's total liability for any claim arising out of or relating to the service is limited to the amount you paid us in the 12 months preceding the claim. We are not liable for indirect, incidental, special, consequential, or punitive damages — including lost profits or data loss — even if advised of the possibility.</p>
        <p>Some jurisdictions do not allow these limitations. In those places, the limits apply to the greatest extent permitted.</p>
      `,
    },
    {
      id: "indemnification",
      title: "11. Indemnification",
      body: `
        <p>You agree to indemnify Lambda, its officers, employees, and agents from any third-party claim arising out of (a) your use of the service in breach of these Terms, (b) your content, or (c) your violation of any applicable law.</p>
      `,
    },
    {
      id: "governing-law",
      title: "12. Governing law & disputes",
      body: `
        <p>These Terms are governed by the laws of the State of Delaware, without regard to conflict-of-laws principles. Any dispute must be resolved through binding arbitration in Wilmington, DE, except that either party may seek injunctive relief in court for IP or confidentiality claims.</p>
        <p>Class actions are waived to the extent permitted by law.</p>
      `,
    },
    {
      id: "changes",
      title: "13. Changes to these terms",
      body: `
        <p>We may update these Terms as the product evolves or the law requires. Material changes will be announced 30 days in advance via email and a banner in the dashboard. Continued use after the effective date constitutes acceptance.</p>
      `,
    },
  ],
  contact: {
    title: "Questions?",
    body:
      'Email <a href="mailto:legal@lambda.dev">legal@lambda.dev</a> or write to Lambda Systems, Inc., Attn: Legal, 200 Berry Street, Suite 400, Brooklyn, NY 11217.',
  },
};
